spec:
  name: arboon-api
  services:
    - name: arboon-api
      github:
        repo: AbdulrahmanNasherAlOtaibi/arbon
        branch: main
        deploy_on_push: true
      source_dir: /
      dockerfile_path: Dockerfile
      http_port: 8080
      instance_size_slug: basic-xxs
      instance_count: 1
      envs:
        - key: NODE_ENV
          value: production
          type: GENERAL
        - key: SESSION_SECRET
          type: SECRET
        - key: DATABASE_URL
          type: SECRET
